image: node

stages:
  - install
  - test
  - build

install:
    stage: install
    script:
        export CI=true;
        npm install;
    artifacts:
        paths:
            - node_modules/
        expire_in: 2 hours

jest-tests:
    stage: test
    script:
        export CI=true;
        npm test -- --coverage;
    artifacts:
        paths:
            - coverage/
        expire_in: 2 days

eslint-tests:
    stage: test
    script:
        export CI=true;
        export DEBUG=eslint:cli-engine;
        ./node_modules/.bin/eslint ./src/;

build:
    stage: build
    script:
        npm run build
    artifacts:
        paths:
            - build/
        expire_in: 1 weeks
