image: node

build:
    stage: build
    script:
        export CI=true;
        npm install;
    artifacts:
        paths:
            - node_modules/
        expire_in: 6 hours

jest-tests:
    stage: test
    script:
        export CI=true;
        npm test;

eslint-tests:
    stage: test
    script:
        export CI=true;
        export DEBUG=eslint:cli-engine;
        ./node_modules/.bin/eslint ./src/;
