language: node_js
node_js:
  - "node"
addons:
    code_climate:
      repo_token: aaacf8e3440b4c2ad2d7ac35e8ff2c9bc95cb70ad33cf23750b8a170a5bef861

jobs:
    include:
      - script: ./node_modules/.bin/eslint .;
      - script: npm test -- --coverage;
      - stage: release
        script: npm pack
        deploy:
          provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: "*.tgz"
          skip_cleanup: true
          on:
            tags: true
      - stage: deploy
        script: cd app && npm run build;
        deploy:
          provider: pages
          local_dir: app/build/
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            branch: master

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
