language: node_js
node_js:
  - "node"
addons:
    code_climate:
      repo_token: aaacf8e3440b4c2ad2d7ac35e8ff2c9bc95cb70ad33cf23750b8a170a5bef861

script:
    npm test -- --coverage;
    ./node_modules/.bin/eslint ./src/;

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
