name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Run static analysis and unittests
      run: |
        npm run lint
        npm test -- --coverage --verbose
    - name: Report coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageLocations: |
          coverage/lcov.info:lcov
  browser-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run robot framework tests
      run: |
        cd tst/
        docker-compose build
        docker-compose up --exit-code-from test
    #     ./screenshots_to_comment.sh
    # - name: Comment pull request
    #   uses: actions/github-script@v3
    #   with:
    #     github-token: ${{secrets.GITHUB_TOKEN}}
    #     script: |
    #       const fs = require('fs');
    #       github.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: fs.readFileSync(`${process.env.GITHUB_WORKSPACE}/tst/comment.md`).toString()
    #       })
    #   if: github.event_name == 'pull_request'
